export const blogObjOne = {
    to: "//keith-hoka.github.io/project0",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "New Life",
    headline: "Me and General Assembly",
    description: "One of the best choice I've ever made in my life -- Join GA and make a career change.",
    buttonLabel: "Read More",
    imgStart: false,
    img: require("../../images/certificate.png"),
    alt: "Project0",
    dark: false,
    primary: false,
    darkText: true,
};

export const blogObjTwo = {
    to: "//foodshoppingapp.herokuapp.com/",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Project 1",
    headline: "Food Shopping Website",
    description: "A shopping app that allows users to create accounts, place orders in shopping cart and access payment for orders.",
    buttonLabel: "Read More",
    imgStart: true,
    img: require("../../images/project1.png"),
    alt: "Project1",
    dark: true,
    primary: true,
    darkText: false,
};

export const blogObjThree = {
    to: "//fir-a4ab6.web.app/",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Project 2",
    headline: "GAmazon (inspired by Amazon)",
    description: "A website that allows users to advertise and sell products. Users may talk to sellers for price negotiation.",
    buttonLabel: "Read More",
    imgStart: false,
    img: require("../../images/project2.png"),
    alt: "Project2",
    dark: false,
    primary: false,
    darkText: true,
};

export const blogObjFour = {
    to: "//travel-blog-ga.netlify.app/",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Project 3",
    headline: "Travel Blog",
    description: "A globe map platform that allows users to sign up and sign in via their email and password to post and share their travel experience.",
    buttonLabel: "Read More",
    imgStart: true,
    img: require("../../images/project3.png"),
    alt: "Project3",
    dark: true,
    primary: true,
    darkText: false,
};