export const projectObjOne = {
    to: "//keith-hoka.github.io/project0",
    to2: "//github.com/Keith-hoka/project0",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Project 0",
    headline: "Tic Tac Toe",
    description: "A game with 3X3 & 5X5 board that allows players to create and store player names, users can even play with computer AI.",
    buttonLabel: "Demo",
    buttonLabel2: "< Code >",
    imgStart: false,
    img: require("../../images/project0.png"),
    alt: "Project0",
    dark: false,
    primary: false,
    darkText: true,
};

export const projectObjTwo = {
    to: "//foodshoppingapp.herokuapp.com/",
    to2: "//github.com/Keith-hoka/Project-1",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Project 1",
    headline: "Food Shopping Website",
    description: "A shopping app that allows users to create accounts, place orders in shopping cart and access payment for orders.",
    buttonLabel: "Demo",
    buttonLabel2: "< Code >",
    imgStart: true,
    img: require("../../images/project1.png"),
    alt: "Project1",
    dark: true,
    primary: true,
    darkText: false,
};

export const projectObjThree = {
    to: "//fir-a4ab6.web.app/",
    to2: "//github.com/Keith-hoka/Project2",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Project 2",
    headline: "GAmazon (inspired by Amazon)",
    description: "A website that allows users to advertise and sell products. Users may talk to sellers for price negotiation.",
    buttonLabel: "Demo",
    buttonLabel2: "< Code >",
    imgStart: false,
    img: require("../../images/project2.png"),
    alt: "Project2",
    dark: false,
    primary: false,
    darkText: true,
};

export const projectObjFour = {
    to: "//travel-blog-ga.netlify.app/",
    to2: "//github.com/Keith-hoka/project3-travel-blog-client",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Project 3",
    headline: "Travel Blog",
    description: "A globe map platform that allows users to sign up and sign in via their email and password to post and share their travel experience.",
    buttonLabel: "Demo",
    buttonLabel2: "< Code >",
    imgStart: true,
    img: require("../../images/project3.png"),
    alt: "Project3",
    dark: true,
    primary: true,
    darkText: false,
};